# Generated by Django 3.1.4 on 2022-03-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0003_auto_20201227_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='item_id',
        ),
    ]
