# Generated by Django 3.1.2 on 2020-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='owner_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='owner_lastname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
