# Generated by Django 3.1.2 on 2020-11-18 19:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201118_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='ug', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
