# Generated by Django 3.1.2 on 2020-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0002_payment_method_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_method',
            name='payment_name',
        ),
        migrations.AddField(
            model_name='payment_method',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_method',
            name='info_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='payment_method',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
