# Generated by Django 3.1.2 on 2020-12-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipping_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
