# Generated by Django 3.1.2 on 2020-12-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20201213_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='amount',
        ),
    ]
