# Generated by Django 3.1.4 on 2020-12-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_remove_shipping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='comment',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
