# Generated by Django 3.1.2 on 2020-11-11 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_method', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('order_date', models.DateField()),
                ('store_status', models.TextField(blank=True, max_length=500, null=True)),
                ('user_status', models.TextField(blank=True, max_length=500, null=True)),
                ('order_totalprice', models.FloatField(default=None)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping_method.shipping_method')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_method.payment_method')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
