# Generated by Django 3.1.2 on 2020-12-12 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201202_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='company_id',
            new_name='shipping_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_totalprice',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='phone_number',
            new_name='user_phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
