# Generated by Django 3.1.2 on 2020-12-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201212_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
