# Generated by Django 3.1.4 on 2020-12-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201213_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='store_status',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_status',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
