# Generated by Django 3.1.4 on 2020-12-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_method', '0003_auto_20201212_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_method',
            name='info_message',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
