# Generated by Django 3.1.2 on 2020-11-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images_urls', models.JSONField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=None)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('stock', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
