# Generated by Django 3.1.4 on 2020-12-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201213_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='images_urls',
            field=models.JSONField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
