# Generated by Django 3.1.4 on 2020-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201227_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='images_urls',
            field=models.JSONField(max_length=10000),
        ),
    ]
